version: '3'
services:
  db:
    container_name: db
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Vitor1998
      - MYSQL_DATABASE=eCommerce
    volumes:
      - /backend/src/database/prisma/migrations:/tmp/database
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_DB=eCommerce
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Vitor1998
      - DATABASE_HOST=db
      - DATABASE_URL=mysql://root:Vitor1998@db:3306/eCommerce?schema=public
    depends_on:
      - db
    volumes:
      - ./backend/src:/app-backend/src
      - ./backend/package.json:/app-backend/package.json
      - ./backend/package-lock.json:/app-backend/package-lock.json
    ports:
      - 3001:3001
