import { IProduct } from '../../../Interfaces/Produtcs';

export const products: IProduct[] = [
  {
    id: 1,
    name: 'Smartphone Galaxy S23 Ultra',
    description: `O smartphone mais poderoso da Samsung, 
com câmera de alta resolução e tela dinâmica.`,
    value: 5999,
    content: 'O melhor smartphone',
  },
  {
    id: 2,
    name: 'iPhone 14 Pro Max',
    description: 'O mais recente smartphone da Apple, com processador A16 Bionic e câmera tripla.',
    content: 'O mais novo iphone da Apple',
    value: 7499,
  },
  {
    id: 3,
    name: 'Google Pixel 7 Pro',
    description: `O novo smartphone da Google com 
câmera avançada e integração total com o Android puro.`,
    content: 'O melhor telefone da Google',
    value: 5699,
  },
  {
    id: 4,
    name: 'Xiaomi 13 Ultra',
    description: `Smartphone premium da Xiaomi, com quatro
câmeras Leica e bateria de longa duração.`,
    content: 'O melhor telefone da Xiaomi',
    value: 5299,
  },
  {
    id: 5,
    name: 'OnePlus 11 Pro',
    description: 'O flagship da OnePlus com desempenho excepcional e display Fluid AMOLED.',
    content: 'O melhor telefone da OnePlus',
    value: 4799,
  },
  {
    id: 6,
    name: 'Sony Xperia 1 V',
    description: 'Smartphone da Sony com tela OLED 4K e foco em fotografia profissional.',
    content: 'O melhor telefone de todos os tempos',
    value: 6199,
  },
  {
    id: 7,
    name: 'Huawei P60 Pro',
    description: 'O topo de linha da Huawei com câmera inovadora e design elegante.',
    content: 'O melhor telefone de todos os ',
    value: 5499,
  },
  {
    id: 8,
    name: 'Oppo Find X6 Pro',
    description: 'Smartphone da Oppo com câmera tripla de 50MP e carregamento rápido de 80W.',
    content: 'O melhor telefone de todos os tempo',
    value: 5199,
  },
  {
    id: 9,
    name: 'Vivo X90 Pro',
    description: 'Smartphone com câmera ZEISS e bateria de 5000mAh para uso prolongado.',
    content: 'O melhor telefone de todos os temp',
    value: 5099,
  },
  {
    id: 10,
    name: 'Motorola Edge 40 Pro',
    description: 'Smartphone com processador Snapdragon 8 Gen 2 e tela pOLED de 144Hz.',
    content: 'O melhor telefone de todos os tem',
    value: 4599,
  },
  {
    id: 11,
    name: 'Asus ROG Phone 7',
    description: 'Smartphone gamer com tela AMOLED de 165Hz e bateria de 6000mAh.',
    content: 'O melhor telefone de todos os te',
    value: 6299,
  },
  {
    id: 12,
    name: 'Realme GT3',
    description: `Smartphone com carregamento ultrarrápido 
de 240W e processador Snapdragon 8+ Gen 1.`,
    content: 'O melhor telefone de todos os t',
    value: 4899,
  },
  {
    id: 13,
    name: 'Lenovo Legion Phone Duel 3',
    description: 'Smartphone voltado para jogos com resfriamento ativo e performance extrema.',
    content: 'O melhor telefone de todos os seculos',
    value: 5399,
  },
  {
    id: 14,
    name: 'Nubia RedMagic 8 Pro',
    description: 'Smartphone gamer com painel AMOLED de 144Hz e gatilhos sensíveis ao toque.',
    content: 'O melhor telefone de todos os milenios',
    value: 5099,
  },
  {
    id: 15,
    name: 'ZTE Axon 40 Ultra',
    description: 'Smartphone com câmera frontal sob a tela e desempenho de topo.',
    content: 'O melhor telefone de todos os anos',
    value: 5499,
  },
  {
    id: 16,
    name: 'Tecno Phantom X2 Pro',
    description: 'Smartphone premium com design diferenciado e câmera retrátil.',
    content: 'O melhor telefone de todos os centries',
    value: 4799,
  },
  {
    id: 17,
    name: 'Infinix Zero Ultra',
    description: 'Smartphone com câmera de 200MP e carregamento rápido de 180W.',
    content: 'O melhor telefone de todos os decadas',
    value: 4999,
  },
  {
    id: 18,
    name: 'Honor Magic5 Pro',
    description: 'Smartphone da Honor com processador Snapdragon 8 Gen 2 e display LTPO.',
    content: 'O melhor telefone de todos os milenarios',
    value: 5799,
  },
  {
    id: 19,
    name: 'Meizu 20 Infinity',
    description: 'Smartphone com tela sem bordas e câmera de 50MP com OIS.',
    content: 'O melhor telefone de todos os fefefe',
    value: 4899,
  },
  {
    id: 20,
    name: 'Samsung Galaxy Z Fold5',
    description: 'Smartphone dobrável com tela interna de 7.6 polegadas e multitarefa avançada.',
    content: 'O melhor telefone de todos os animal',
    value: 8998,
  },
];
